### ISSUE TITLE
Should the verification algorithm be salted

### ISSUE THREAD

**Issue by mgintoki** [DimensionDev/RedPacket#43]
Should the verification algorithm be salted? For example, add the id of the red envelope with receiver‘s account to hash? The current algorithm seems to be that users can use a certain signature to claim multiple red envelopes unlimited times

**Comment by yisiliu** [comment]
the idea is that: we will generate an arbitrary private key **sk** for each red packet and send the public key **pk** derived by this unique private key to the smart contract  at https://github.com/DimensionDev/RedPacket/blob/master/contracts/redpacket.sol#L100. Users need this private key **sk** to sign a typed message using the logic at https://github.com/DimensionDev/RedPacket/blob/master/contracts/redpacket.sol#L163 to verify themselves. 

> The current algorithm seems to be that users can use a certain signature to claim multiple red envelopes unlimited times

as stated above, keys vary for each red packet so this shouldn't be a problem

**Comment by yisiliu** [comment]
@mgintoki does it solve your problem? Please let us know before closing the issue next. Thanks

**Comment by mgintoki** [comment]
Very helpful. Thank you very much @yisiliu
